apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:{{ .Values.app.port }}"
            - name: ConnectionStrings__App
              value: "Server=mssql;Database=ManagementSystemDB;User Id=sa;Password={{ .Values.mssql.password }};TrustServerCertificate=True;"
            - name: ConnectionStrings__Master
              value: "Server=mssql;User Id=sa;Password={{ .Values.mssql.password }};TrustServerCertificate=True;"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: {{ .Values.mssql.image }}
          ports:
            - containerPort: {{ .Values.mssql.port }}
          env:
            - name: SA_PASSWORD
              value: {{ .Values.mssql.password | quote }}
            - name: ACCEPT_EULA
              value: "Y"